### PR TITLE
Add toggle button to toggle labels

### PR DESCRIPTION
**Pull request by caseymh**
Add the ability to toggle labels by clicking a button or by shortcut t.

### CODE REVIEW

**Comment by caseymh** [comment]
FROM CAPAJON/R6MAPS:
YOU:

It's been awhile but I finally have some time to look at this. I have a few questions:  

1. Why did you decide to not change the background of the toggle button on focus? 
2. Is there a reason you don't also prevent the background from  changing on hover? (in practice, this only allows the button to change  color the first time it's clicked, so it looks like it's a bug). 
3. Why are you putting DisplayNone as the default twice (one via data-prevRoomStyle and one via a ternary operator in setupToggleClickEvent)?  

Other than that, the only problems I can find are from the original implementation for room styles.
--


ME:

1.    I didn't change the background on focus because when I did it would change to blue and then it would always stay blue. Looking at it closer it stays blue until you click another button but if you click somewhere on the map it doesn't change back to white. As it is a toggle button I didn't think it should stay highlighted after you click it.
2.    I didn't prevent the background from changing on hover so that it would be more uniform with the other buttons, since they change when hovered over. There is a bug here as if you are hovering and it is in focus it won't change color but if you focus on something else it will.
3.   I think I defaulted it twice because I did the HTML part first and then when I was doing setupToggleClickEvent I put it there to be more robust. I can take it out of the HTML element if you want.

**Comment by purechaose** [comment]
So after digging into the stylesheet a bit, it turns out the reason that buttons stay blue after you press them is because of the `&:focus` in [this line](https://github.com/purechaose/r6maps/pull/3/files#diff-0ab09603e880dbd574cd6114f1325cbeR210). If you get rid of it, you don't need to specify `:hover` and `:hover:focus` separately (and IMO the buttons should stay blue after gaining focus anywhere).

New concern:
1. The toggle button text and title text should be translatable. To do this I would first recommend moving the call to `toggle.populate()` from the init down into `loadMap`, where the floors are populated. Then just use `R6LangTerms` much like in other places, and edit `lang-terms.js` accordingly (and the corresponding js files for languages you know, if any). You can either put it under general or its own sub object. 

I thought I had more concerns, but I guess not. Once that's done it should be ready to merge in.

**Comment by caseymh** [comment]
Ok I will take a look at that

On May 17, 2019 6:55 PM, purechaose <notifications@github.com> wrote:

So after digging into the stylesheet a bit, it turns out the reason that buttons stay blue after you press them is because of the &:focus in this line<https://github.com/purechaose/r6maps/pull/3/files#diff-0ab09603e880dbd574cd6114f1325cbeR210>. If you get rid of it, you don't need to specify :hover and :hover:focus separately (and IMO the buttons should stay blue after gaining focus anywhere).

New concern:

  1.  The toggle button text and title text should be translatable. To do this I would first recommend moving the call to toggle.populate() from the init down into loadMap, where the floors are populated. Then just use R6LangTerms much like in other places, and edit lang-terms.js accordingly (and the corresponding js files for languages you know, if any). You can either put it under general or its own sub object.

I thought I had more concerns, but I guess not. Once that's done it should be ready to merge in.

**Comment by caseymh** [comment]
I added the language support.
Looking at the styling closer I agree that removing that line would make it so the focus doesn't change button color to blue. I also agree that buttons should be changed to blue on focus, as it is currently doing. I however feel having it work this way for the toggle button is a little counter intuitive. Changing the color on focus, to me, feels like it is showing it is on. In the case of a toggle button however, it isn't really on but toggling off or on. Because of this I think it makes more sense to just have hover change the color for toggle buttons and keep focus changing the color for all other buttons. 
This is my opinion. If you still want me to change it so they are all the same I will do so and commit that.

**Pull request merged**
